server {
    listen 80;
    server_name _;

    location = / {
        return 302 /commons-sim/;
    }

    location /commons-sim/ {
        alias /usr/share/nginx/html/commons-sim/;
        index index.html;
        try_files $uri $uri/ /commons-sim/index.html;
    }
}
