import { z } from "zod";

export const DesignModeSchema = z.enum(["dream", "soft-sim", "challenge", "professional", "research"]);
export type DesignMode = z.infer<typeof DesignModeSchema>;

export const ValidationSeveritySchema = z.enum(["info", "warning", "error", "blocking"]);
export type ValidationSeverity = z.infer<typeof ValidationSeveritySchema>;

export const ModePolicySchema = z.object({
  policyVersion: z.literal(1),
  mode: DesignModeSchema,
  label: z.string().min(1),
  description: z.string().min(1),
  allowPartialGraphs: z.boolean(),
  allowUnconnectedTerminals: z.boolean(),
  allowExperimentalModules: z.boolean(),
  allowFantasyGeometry: z.boolean(),
  allowMissingCostData: z.boolean(),
  allowMissingRealWorldBinding: z.boolean(),
  allowAiDraftArtifacts: z.boolean(),
  canSaveWithWarnings: z.boolean(),
  canSimulateWithWarnings: z.boolean(),
  canSubmitToLeaderboard: z.boolean(),
  canExportProfessionalReport: z.boolean(),
  lockedFieldPaths: z.array(z.string()),
});
export type ModePolicy = z.infer<typeof ModePolicySchema>;

export function getDefaultModePolicy(mode: DesignMode): ModePolicy {
  const policies: Record<DesignMode, ModePolicy> = {
    dream: {
      policyVersion: 1,
      mode: "dream",
      label: "Dream Mode",
      description: "Creative sandbox for incomplete and imaginative designs.",
      allowPartialGraphs: true,
      allowUnconnectedTerminals: true,
      allowExperimentalModules: true,
      allowFantasyGeometry: true,
      allowMissingCostData: true,
      allowMissingRealWorldBinding: true,
      allowAiDraftArtifacts: true,
      canSaveWithWarnings: true,
      canSimulateWithWarnings: false,
      canSubmitToLeaderboard: false,
      canExportProfessionalReport: false,
      lockedFieldPaths: [],
    },
    "soft-sim": {
      policyVersion: 1,
      mode: "soft-sim",
      label: "Soft Simulation",
      description: "Explains likely consequences without treating warnings as blockers.",
      allowPartialGraphs: true,
      allowUnconnectedTerminals: true,
      allowExperimentalModules: true,
      allowFantasyGeometry: false,
      allowMissingCostData: true,
      allowMissingRealWorldBinding: true,
      allowAiDraftArtifacts: true,
      canSaveWithWarnings: true,
      canSimulateWithWarnings: true,
      canSubmitToLeaderboard: false,
      canExportProfessionalReport: false,
      lockedFieldPaths: [],
    },
    challenge: {
      policyVersion: 1,
      mode: "challenge",
      label: "Challenge Mode",
      description: "Fair benchmark mode with locked scenario assumptions.",
      allowPartialGraphs: false,
      allowUnconnectedTerminals: false,
      allowExperimentalModules: false,
      allowFantasyGeometry: false,
      allowMissingCostData: false,
      allowMissingRealWorldBinding: true,
      allowAiDraftArtifacts: false,
      canSaveWithWarnings: true,
      canSimulateWithWarnings: false,
      canSubmitToLeaderboard: true,
      canExportProfessionalReport: false,
      lockedFieldPaths: [
        "compiledScenario.householdCount",
        "compiledScenario.householdMix",
        "compiledScenario.wageModel",
        "compiledScenario.utilities",
      ],
    },
    professional: {
      policyVersion: 1,
      mode: "professional",
      label: "Professional Mode",
      description: "Requires provenance, cost data, and real-world binding before export.",
      allowPartialGraphs: false,
      allowUnconnectedTerminals: false,
      allowExperimentalModules: false,
      allowFantasyGeometry: false,
      allowMissingCostData: false,
      allowMissingRealWorldBinding: false,
      allowAiDraftArtifacts: false,
      canSaveWithWarnings: false,
      canSimulateWithWarnings: false,
      canSubmitToLeaderboard: false,
      canExportProfessionalReport: true,
      lockedFieldPaths: [],
    },
    research: {
      policyVersion: 1,
      mode: "research",
      label: "Research Mode",
      description: "Requires reproducibility and explicit assumptions.",
      allowPartialGraphs: false,
      allowUnconnectedTerminals: false,
      allowExperimentalModules: true,
      allowFantasyGeometry: false,
      allowMissingCostData: false,
      allowMissingRealWorldBinding: false,
      allowAiDraftArtifacts: false,
      canSaveWithWarnings: false,
      canSimulateWithWarnings: false,
      canSubmitToLeaderboard: false,
      canExportProfessionalReport: false,
      lockedFieldPaths: [],
    },
  };

  return ModePolicySchema.parse(policies[mode]);
}
