name: api-container
on:
  push:
  pull_request:

jobs:
  build_api_container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build API image
        run: docker build -f Dockerfile.api -t commons-sim:api-ci .
