name: deploy-staging

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  deploy_staging:
    if: github.ref == 'refs/heads/staging'
    runs-on: ubuntu-latest
    environment:
      name: staging
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm build
      - run: echo "Deploying staging to staging environment"
